title: Chen Jinghao's Homepage
page-top-title: Chen Jinghao
top-section-bg-text: Computer Science
home-subtitle: Chen Jinghao&ensp;|&ensp;陈靖昊
copyright-text: '&copy; Chen Jinghao 2007. All Rights Reserved.'
